version: "3.9"

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.8.0-pre
    volumes:
      - /srv/var/cardano/state-sanchonet:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always

  hydra-explorer:
    image: ghcr.io/input-output-hk/hydra-explorer:unstable
    volumes:
    - /srv/var/cardano/state-sanchonet:/data
    ports:
      - "80:8080"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "4"
      , "--api-port", "8080"
      # NOTE: Block in which current master scripts were published
      , "--start-chain-from", "21830575.4fa28d6c6f6541fd5c73d715d69f3dd7751e7b4d7dc1213cb02d30c5a0db609b"
      ]
    restart: always
