# Build executables that can be used on any Linux with 64bit CPUs.
#
# Produces static ELF binary using MuslC which includes all needed libraries
# statically linked into it.
name: Linux x86_64

on:
  push:
    branches:
    - "**"
    tags:
    - "*.*.*"

jobs:
  build-executables:
    name: "Build x86_64-linux static executables"
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        # Also ensure we have all history with all tags
        fetch-depth: 0

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: ❄ Cachix cache of nix derivations
      uses: cachix/cachix-action@v13
      with:
        name: cardano-scaling
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: ❄ Build static executables
      run: |
        nix build .#release-static

    # XXX: Why unzip https://github.com/actions/upload-artifact/issues/39
    - name: 🤐 Unzip and prepare upload
      run: |
        echo "VERSION=$(git describe --always ${{ github.ref }})" >> "$GITHUB_ENV"
        unzip result/*.zip -d out

    - name: 💾 Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: hydra-x86_64-linux-${{ env.VERSION }} # automatically zips
        path: out/*
