name: "Explorer"
on:
  push:
    branches: ["upgrade-explorer-workflow"]
  workflow_run:
    workflows: ["Docker"]
    branches: ["master"]
    types:
      - completed

jobs:
  explorer:
    name: "Deploy"
    runs-on: explorer
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd .github/workflows/explorer
        docker compose pull
        docker compose up -d
