# Build executables to be used on MacOS with Apple silicon (aarch64) CPUs.
#
# As the Darwin platform is not great for static linking, we stick with
# dynamically linked binaries and also package the nix-provided .dyn libraries.
name: MacOS ARM64

on:
  push:
    branches:
    - "**"
    tags:
    - "*.*.*"

jobs:
  build-executables:
    name: "Build aarch64-darwin dynamic executables"
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: ❄ Cachix cache of nix derivations
      uses: cachix/cachix-action@v12
      with:
        name: cardano-scaling
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: ❄ Build executables
      run: |
        mkdir -p bin/
        nix build .#hydra-node && cp result/bin/* bin/
        nix build .#hydra-tui && cp result/bin/* bin/

    - name: ❄ Collect runtime libraries from /nix/store
      run: |
        nix shell nixpkgs#python311Packages.pylddwrap --command sh <<EOF
          pylddwrap -f json bin/hydra-node | jq -r '.[].path | select(. != "None")' | xargs -I{} cp {} bin/
        EOF

    - name: 💾 Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: hydra-aarch64-darwin
        path: |
          ./bin
