# Build executables to be used on MacOS with Apple silicon (aarch64) CPUs.
#
# Produces a dynamic Mach-O binary which is still dynamically linked against
# system dependencies, but all third-party libraries are statically linked.
name: MacOS ARM64

on:
  push:
    branches:
    - "**"
    tags:
    - "*.*.*"

jobs:
  build-executables:
    name: "Build aarch64-darwin dynamic executables"
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: ❄ Cachix cache of nix derivations
      uses: cachix/cachix-action@v12
      with:
        name: cardano-scaling
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: ❄ Build executables
      run: |
        nix build .#release

    - name: 💾 Upload executables
      uses: actions/upload-artifact@v3
      with:
        path: result/*.zip
